openapi: 3.1.0
info:
  title: vague-chipmunk
  version: 1.0.0
paths:
  /hello:
    get:
      operationId: getHello
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 'Invalid value for: query parameter name'
          content:
            text/plain:
              schema:
                type: string
  /books/list/all:
    get:
      operationId: getBooksListAll
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    AName:
      required:
      - s
      type: object
      properties:
        s:
          type: string
    Book:
      required:
      - title
      - year
      - a1
      - a2
      - b1
      - b2
      - c1
      - c2
      - d1
      - d2
      type: object
      properties:
        title:
          type: string
        year:
          type: integer
          format: int32
        a1:
          $ref: '#/components/schemas/CcA'
        a2:
          $ref: '#/components/schemas/CcA'
        b1:
          $ref: '#/components/schemas/CcB'
        b2:
          $ref: '#/components/schemas/CcB'
        c1:
          $ref: '#/components/schemas/CcC'
        c2:
          $ref: '#/components/schemas/CcC'
        d1:
          $ref: '#/components/schemas/CcD'
        d2:
          $ref: '#/components/schemas/CcD'
    CcA:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    CcB:
      required:
      - name
      - aName
      type: object
      properties:
        name:
          type: string
        aName:
          $ref: '#/components/schemas/CcName'
    CcC:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    CcD:
      required:
      - name
      - aName
      type: object
      properties:
        name:
          type: string
        aName:
          $ref: '#/components/schemas/CcName'
    CcName:
      deprecated: true
      oneOf:
      - $ref: '#/components/schemas/AName'
