openapi: 3.1.0
info:
  title: vague-chipmunk
  version: 1.0.0
paths:
  /hello:
    get:
      operationId: getHello
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 'Invalid value for: query parameter name'
          content:
            text/plain:
              schema:
                type: string
  /books/list/all:
    get:
      operationId: getBooksListAll
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    Author:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    Book:
      required:
      - title
      - year
      - author
      type: object
      properties:
        title:
          type: string
        year:
          type: integer
          format: int32
        author:
          $ref: '#/components/schemas/Author'
